### Import NumPy as np

In [6]:
import numpy as np

## Create an array of 10 zeros¶

In [7]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

## Create an array of 10 ones

In [8]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

## Create an array of 10 fives

In [10]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [12]:
np.zeros(10)+5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

##  Create an array of the integers from 10 to 50

In [24]:
arr = np.arange(10,50)
ranarr = np.random.randint(10,50,10)  ### no need to do

In [25]:
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [26]:
arr = np.arange(10,50)

In [27]:
arr

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

###  Create an array of all the even integers from 10 to 50


In [33]:
arr.dtype

dtype('int32')

In [41]:
even_no=[num for num in range(10,51)
        if num %2==0]
print(even_no)

[10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32, 34, 36, 38, 40, 42, 44, 46, 48, 50]


### Create a 3x3 matrix with values ranging from 0 to 8

In [50]:
arr = np.arange(0,9)


In [51]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

In [52]:
arr.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [53]:
my_matrix = [[0,1,2],[3,4,5],[6,7,8]]
my_matrix

[[0, 1, 2], [3, 4, 5], [6, 7, 8]]

In [54]:
np.array(my_matrix)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### Create a 3x3 identity matrix¶

In [55]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

####  Use NumPy to generate a random number between 0 and 1

In [65]:
np.random.rand(1)

array([0.65975413])

###   Use NumPy to generate an array of 25 random numbers sampled from a standard normal distribution

In [57]:
np.random.randn(25)

array([ 0.25313662, -2.04240382,  0.65929708, -0.23686671,  0.33770978,
        0.43691533, -0.3225899 , -0.39692219,  1.02546833,  1.33007449,
       -0.01172996,  0.73837216, -0.58439189,  1.25568621,  0.83864076,
        1.46189034,  1.66927266,  1.24405234,  1.27534308,  1.17856363,
        1.04039458, -0.6381902 ,  0.13681376,  0.22604777, -1.96357947])

###  Create the following matrix:

In [69]:
np.arange(1,101).reshape(10,10)

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [70]:
np.arange(1,101).reshape(10,10)/100

array([[0.01, 0.02, 0.03, 0.04, 0.05, 0.06, 0.07, 0.08, 0.09, 0.1 ],
       [0.11, 0.12, 0.13, 0.14, 0.15, 0.16, 0.17, 0.18, 0.19, 0.2 ],
       [0.21, 0.22, 0.23, 0.24, 0.25, 0.26, 0.27, 0.28, 0.29, 0.3 ],
       [0.31, 0.32, 0.33, 0.34, 0.35, 0.36, 0.37, 0.38, 0.39, 0.4 ],
       [0.41, 0.42, 0.43, 0.44, 0.45, 0.46, 0.47, 0.48, 0.49, 0.5 ],
       [0.51, 0.52, 0.53, 0.54, 0.55, 0.56, 0.57, 0.58, 0.59, 0.6 ],
       [0.61, 0.62, 0.63, 0.64, 0.65, 0.66, 0.67, 0.68, 0.69, 0.7 ],
       [0.71, 0.72, 0.73, 0.74, 0.75, 0.76, 0.77, 0.78, 0.79, 0.8 ],
       [0.81, 0.82, 0.83, 0.84, 0.85, 0.86, 0.87, 0.88, 0.89, 0.9 ],
       [0.91, 0.92, 0.93, 0.94, 0.95, 0.96, 0.97, 0.98, 0.99, 1.  ]])

###   Create an array of 20 linearly spaced points between 0 and 1:

In [71]:
np.linspace(0,1,20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

###    Numpy Indexing and Selection
Now you will be given a few matrices, and be asked to replicate the resulting matrix outputs:

In [72]:
arr=np.arange(1,26).reshape(5,5)

In [73]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [74]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [75]:
arr2d=arr.reshape(5,5)

In [79]:
arr2d[2:5,1:5]

array([[12, 13, 14, 15],
       [17, 18, 19, 20],
       [22, 23, 24, 25]])

In [89]:
arr[3][4]

20

In [90]:
###  # WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [91]:
arr[3][4]

20

In [92]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [93]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [166]:
arr2d[0:3,1]

array([ 2,  7, 12])

In [201]:

# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [204]:
arr2d[4:]

array([[21, 22, 23, 24, 25]])

In [205]:
# WRITE CODE HERE THAT REPRODUCES THE OUTPUT OF THE CELL BELOW
# BE CAREFUL NOT TO RUN THE CELL BELOW, OTHERWISE YOU WON'T
# BE ABLE TO SEE THE OUTPUT ANY MORE

In [207]:
arr2d[3:]

array([[16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

####   Get the sum of all the values in mat

In [208]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [209]:
arr.sum()

325

####  Get the standard deviation of the values in mat

In [211]:
arr.std()

7.211102550927978

###   Get the sum of all the columns in mat

In [221]:
arr2d.sum(axis=1)

array([ 15,  40,  65,  90, 115])

In [222]:
arr[:,4:]

array([[ 5],
       [10],
       [15],
       [20],
       [25]])

In [223]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [224]:
arr.sum(axis=0)

array([55, 60, 65, 70, 75])

In [244]:
df=arr.sum(axis=1)

In [247]:
df

array([ 15,  40,  65,  90, 115])

In [253]:
array = np.array([[1, 2, 3, 4, 5],
                  [6, 7, 8, 9, 10],
                  [11, 12, 13, 14, 15],
                  [16, 17, 18, 19, 20],
                  [21, 22, 23, 24, 25]])

In [258]:
sum_first_column = np.sum(array[:, 0])
print(f"The sum of the first column is: {sum_first_column}")

The sum of the first column is: 55


In [259]:
sum_first_row = np.sum(array[0, :])
print(f"The sum of the first row is: {sum_first_row}")

The sum of the first row is: 15


In [260]:
arr = np.array([2, 7, 12])

In [262]:
reshaped_arr = arr.reshape(3, 1)
print("\nReshaped array:")
print(reshaped_arr)


Reshaped array:
[[ 2]
 [ 7]
 [12]]


In [263]:
pwd

'C:\\Users\\admin\\Downloads'